### ISSUE TITLE
SubmissionBlock 컴포넌트 구현

### ISSUE THREAD

**Issue by mubun** [0NYE/FPS-frontend#20]
## Description
전체적인 결과를 보여주는 박스입니다
## Todo List
점수들을 보여주는 circlechart 배치
pass기준 넘으면 통과 띄우기
기준 미달시 실패 및 실패이유 띄우기
## ETC
그런데 실패 기준을 저희가 따로 정했었나요?
기억이 안나서 혹시 알고계시면 알려주시면 감사하겠습니당

**Comment by cheoljunpark** [comment]
실패 기준은 막연히 100점 만점 중에 60점 미만이면 실패라고 정한걸로 알고 있습니다.

**Comment by mubun** [comment]
아항 정보 감사드립니당. 실패기준에 대해서 얘기해봐야겠네여
